server:
  port: 8378
  #自定义异常
  error:
    include-exception: true
    include-message: always


#配置MySQL数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mingxy925871


  data:
    mongodb:
      #      uri: mongodb://root:123456@127.0.0.1:27017/admin
      uri: mongodb://root:123456@127.0.0.1:27017/dataway2

