server:
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: test
  ## 此处填写你自己的七牛云 secret key
  secretKey: test
  ## 此处填写你自己的七牛云 bucket
  bucket: test
  ## 此处填写你自己的七牛云 域名
  prefix: te
spring:
  servlet:
    multipart:
      enabled: true
      location: /root/ubloadJar/file
      file-size-threshold: 5MB
      max-file-size: 20MB