server:
  port: 8852

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_hello?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mingxy925871
  jpa:
    hibernate:
      ddl-auto: update  #第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: false

smb:
  jobSourcePath: smb://T480S:ktkj123456@172.20.10.2/test/
  sourcePath: smb://T480S:ktkj123456@172.20.10.2/test/
  targetPath: smb://T480S:ktkj123456@172.20.10.2/test1/
  sync_schedule:  "* */5 * * * ?"
  clean_schedule: "0 0 2 1 * ?"
logging:
  file:
    path: log
